server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

# Esta es la parte clave:
# Le dice a Promtail que use el Docker Socket para
# encontrar otros contenedores y leer sus logs (stdout/stderr)
- job_name: containers
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
  relabel_configs:
    - source_labels: [__meta_docker_container_name]
      regex: /(.+)
      target_label: 'container'
    # Esta línea es para que coincida con el job de Prometheus
    - source_labels: [__meta_docker_container_compose_service]
      target_label: 'job'